import { Chain } from '../types';

export const SUPPORTED_CHAINS: Chain[] = [
  {
    id: 'eth',
    chainId: 1,
    name: 'Ethereum',
    symbol: 'ETH',
    color: '#627EEA',
    icon: 'Ξ',
  },
  {
    id: 'bsc',
    chainId: 56,
    name: 'BNB Chain',
    symbol: 'BNB',
    color: '#F3BA2F',
    icon: '⬡',
  },
  {
    id: 'polygon',
    chainId: 137,
    name: 'Polygon',
    symbol: 'MATIC',
    color: '#8247E5',
    icon: '⬟',
  },
  {
    id: 'arbitrum',
    chainId: 42161,
    name: 'Arbitrum',
    symbol: 'ARB',
    color: '#12AAFF',
    icon: '◈',
  },
  {
    id: 'avalanche',
    chainId: 43114,
    name: 'Avalanche',
    symbol: 'AVAX',
    color: '#E84142',
    icon: '▲',
  },
  {
    id: 'optimism',
    chainId: 10,
    name: 'Optimism',
    symbol: 'OP',
    color: '#FF0420',
    icon: '◎',
  },
  {
    id: 'tron',
    chainId: 'tron',
    name: 'Tron',
    symbol: 'TRX',
    color: '#EB0029',
    icon: '◈',
  },
];

export const RISK_FACTOR_LABELS: Record<string, string> = {
  blacklist_doubt: 'Blacklist Suspicion',
  blackmail_activities: 'Blackmail Activities',
  cybercrime: 'Cybercrime',
  darkweb_transactions: 'Darkweb Transactions',
  financial_crime: 'Financial Crime',
  fake_kyc: 'Fake KYC',
  gas_price_manipulation: 'Gas Price Manipulation',
  honeypot_related_address: 'Honeypot Related',
  malicious_mining_activities: 'Malicious Mining',
  mixer: 'Mixer / Tumbler',
  money_laundering: 'Money Laundering',
  number_of_malicious_contracts_created: 'Malicious Contracts Created',
  phishing_activities: 'Phishing Activities',
  reinit: 'Reinit Attack',
  sanctioned: 'Sanctioned Address',
  stealing_attack: 'Stealing Attack',
  fake_token: 'Fake Token',
  contract_address: 'Contract Address',
};

export const RISK_FACTOR_DESCRIPTIONS: Record<string, string> = {
  blacklist_doubt: 'Address is suspected to be on a blacklist',
  blackmail_activities: 'Address has been involved in blackmail or extortion',
  cybercrime: 'Address is linked to cybercriminal activities',
  darkweb_transactions: 'Address has transactions with darkweb entities',
  financial_crime: 'Address is associated with financial crimes',
  fake_kyc: 'Address has been flagged for fake identity verification',
  gas_price_manipulation: 'Address has manipulated gas prices maliciously',
  honeypot_related_address: 'Address is related to honeypot scam contracts',
  malicious_mining_activities: 'Address is involved in malicious mining',
  mixer: 'Address has used coin mixers or tumblers for obfuscation',
  money_laundering: 'Address is suspected of money laundering',
  number_of_malicious_contracts_created: 'Number of malicious smart contracts deployed',
  phishing_activities: 'Address has been involved in phishing attacks',
  reinit: 'Address is involved in reinit attacks',
  sanctioned: 'Address is on an official sanctions list (OFAC, etc.)',
  stealing_attack: 'Address has conducted stealing attacks',
  fake_token: 'Address is associated with fake/counterfeit tokens',
  contract_address: 'This is a smart contract address',
};
